# Strictly use GitHub FreeBSD source for Unikraft

################################################################################
# Library registration
################################################################################
$(eval $(call addlib_s,libfreebsdlibc,$(CONFIG_LIBFREEBSDLIBC)))

################################################################################
# Fetch from GitHub FreeBSD source repository (only URL, no local fallback)
################################################################################
FREEBSDLIBC_VERSION := main
FREEBSDLIBC_URL := https://github.com/freebsd/freebsd-src/archive/refs/heads/main.tar.gz
FREEBSDLIBC_PATCHDIR := $(LIBFREEBSDLIBC_BASE)/patches

$(eval $(call fetch,libfreebsdlibc,$(FREEBSDLIBC_URL)))
$(eval $(call patch,libfreebsdlibc,$(FREEBSDLIBC_PATCHDIR),freebsd-src-main))

FREEBSDLIBC_SUBDIR := freebsd-src-main
FREEBSDLIBC_LIBCDIR := $(LIBFREEBSDLIBC_ORIGIN)/$(FREEBSDLIBC_SUBDIR)/lib/libc
FREEBSDLIBC_LIBSYSDIR := $(LIBFREEBSDLIBC_ORIGIN)/$(FREEBSDLIBC_SUBDIR)/lib/libsys

################################################################################
# Includes (stdio, string, and all needed for printf and string functions)
################################################################################
# Correct order: source root, sys/x86/include, sys/sys, then the rest
LIBFREEBSDLIBC_COMMON_INCLUDES-y := -I$(FREEBSDLIBC_SRCDIR)
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_SRCDIR)/sys/amd64/include
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_SRCDIR)/sys/x86/include
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_SRCDIR)/sys/sys
# FreeBSD libc specific includes
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_LIBCDIR)/include
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_LIBCDIR)/sys
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_LIBCDIR)/stdio
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_LIBCDIR)/stdlib
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_LIBCDIR)/string
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_LIBCDIR)/csu
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(LIBFREEBSDLIBC_BASE)/include
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(LIBFREEBSDLIBC_LIBSYSDIR)

# FreeBSD system headers (for stdarg.h, stdint.h, etc.)
FREEBSDLIBC_SRCDIR := $(LIBFREEBSDLIBC_ORIGIN)/$(FREEBSDLIBC_SUBDIR)
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_SRCDIR)/sys
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(FREEBSDLIBC_SRCDIR)/sys/x86
# Additional include paths for x86 architecture
# (already added sys/x86/include and sys/amd64/include above)

# Unikraft glue headers
LIBFREEBSDLIBC_COMMON_INCLUDES-y += -I$(LIBFREEBSDLIBC_BASE)/include

CINCLUDES-$(CONFIG_LIBFREEBSDLIBC)   += $(LIBFREEBSDLIBC_COMMON_INCLUDES-y)
CXXINCLUDES-$(CONFIG_LIBFREEBSDLIBC) += $(LIBFREEBSDLIBC_COMMON_INCLUDES-y)

################################################################################
# Global flags for FreeBSD libc
################################################################################
LIBFREEBSDLIBC_CFLAGS-y += -D__UNIKRAFT__
LIBFREEBSDLIBC_CFLAGS-y += -ffreestanding
LIBFREEBSDLIBC_CFLAGS-y += -fno-builtin
LIBFREEBSDLIBC_CFLAGS-y += -DMISSING_SYSCALL_NAMES

CFLAGS-$(CONFIG_LIBFREEBSDLIBC)   += $(LIBFREEBSDLIBC_CFLAGS-y)
CXXFLAGS-$(CONFIG_LIBFREEBSDLIBC) += $(LIBFREEBSDLIBC_CFLAGS-y)

################################################################################
# FreeBSD libc sources (for printf, puts, and all string functions)
################################################################################
# Startup code (CSU - C Startup)
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/csu/libc_start1.c

# Stdio functions
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/stdio/printf.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/stdio/vfprintf.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/stdio/puts.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/stdio/putchar.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/stdio/getchar.c

# String functions (all basic string/memory ops)
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strlen.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strcpy.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strncpy.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strcat.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strncat.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strcmp.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strncmp.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strchr.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strrchr.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/strstr.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/memcpy.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/memmove.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/memset.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/memcmp.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/string/memchr.c

# Stdlib functions
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/stdlib/exit.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/stdlib/abort.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/stdlib/atexit.c

# System calls (basic ones)
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/sys/write.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/sys/read.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/sys/open.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/sys/close.c
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBCDIR)/sys/exit.c

# Libsys (syscall interface)
LIBFREEBSDLIBC_SRCS-y += $(FREEBSDLIBC_LIBSYSDIR)/_libsys.c

# Unikraft glue code
LIBFREEBSDLIBC_SRCS-y += $(LIBFREEBSDLIBC_BASE)/src/glue/plat.c
LIBFREEBSDLIBC_SRCS-y += $(LIBFREEBSDLIBC_BASE)/src/glue/syscall.c
LIBFREEBSDLIBC_SRCS-y += $(LIBFREEBSDLIBC_BASE)/src/glue/libc_start1.c

SRCS-$(CONFIG_LIBFREEBSDLIBC) += $(LIBFREEBSDLIBC_SRCS-y)
